### ISSUE TITLE
Automate docker image build.

### ISSUE THREAD

**Issue by pbalogh-sa** [banzaicloud/jwt-to-rbac#24]
**Is your feature request related to a problem? Please describe.**
Automate docker image build.

**Describe the solution you'd like to see**
Trigger a docker image building and pushing if a tag is created.

**Describe alternatives you've considered**
Manually build and push the docker image

**Comment by vigohe** [comment]
@pbalogh-sa  Will you consider to upload it to the new github registry, instead of dockerhub?

**Comment by pbalogh-sa** [comment]
> @pbalogh-sa Will you consider to upload it to the new github registry, instead of dockerhub?

Yes, I'm planning to use gh actions and gh registry.

**Comment by pbalogh-sa** [comment]
@vigohe Now, you can pull the image from GitHub registry as well. (0.3.0 or latest)
`docker pull ghcr.io/banzaicloud/jwt-to-rbac:0.3.0`
