### ISSUE TITLE
Changing log level and applying it with helm does not take an effect

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#39]
**Describe the bug**
Changing log level and applying it with helm does not take an effect.

**Steps to reproduce the issue:**
1. In values.yaml change log.level to debug
1. helm upgrade --install
1. observe that ConfigMap has changed but application still does not print debug level messages.

**Expected behaviour**
Application changes it log level

**Comment by pbalogh-sa** [comment]
@j-zimnowoda Thaks for reporting this. We will fix it soon.
