### ISSUE TITLE
Verify JWT with any OIDC provider

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#41]
**Is your feature request related to a problem? Please describe.**
From documentation, it seems that this solution works only with Dex. 

**Describe the solution you'd like to see**
I would go for more generic approach as verifying JWT is quite straight forward.

**Comment by pbalogh-sa** [comment]
You're right. The jwt-to-rbac uses [go-oidc](https://github.com/coreos/go-oidc) package for verifying the token. So, some naming changes will solve this.

**Comment by j-zimnowoda** [comment]
Indeed, yesterday I successfully run it with keycloak.
Maybe changing `tokenhandler.dex` to just `oidc` would be enough.
