### ISSUE TITLE
Document required user claims

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#42]
**Is your feature request related to a problem? Please describe.**
Required user claims are not documented.
E.g.: What are `FederatedClaims` and how they are used by jwt-to-rbac?

**Describe the solution you'd like to see**
All requirements that OIDC provider needs to meet in order to be compatible with jwt-to-rbac

**Comment by pbalogh-sa** [comment]
@j-zimnowoda Thanks. We will update the documentation soon.
