### ISSUE TITLE
The response for HTTP POST /rbac/

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#45]
Hi, first of all thanks for documentation update.
I see a big potential in this project, so I would to contribute more ;).

**Is your feature request related to a problem? Please describe.**
After sending ID_TOKEN to  /rbac/ endpoint, a new Service Account (SA) is created.
We need to know its name in order to ask request SA token. Unfortunately, the response does not contain SA name, thus a user needs to figure it out.

**Describe the solution you'd like to see**
I propose to add a new property: `ServiceAccount` to POST /rbac/ response:
```json
{
    "Email": "janedoe@example.com",
    "Groups": [
        "admins",
        "developers"
    ],
    "FederatedClaims": {
        "connector_id": "ldap",
        "user_id": "cn=jane,ou=People,dc=example,dc=org"
    }
    // New property
    "ServiceAccount": "janedoe-example-com"
}
```

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by pbalogh-sa** [comment]
Thanks @j-zimnowoda ! Good idea. Every contribution is welcome.
