### ISSUE TITLE
Add openapi v3 spec

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#46]
**Is your feature request related to a problem? Please describe.**
- Learning about api endpoints, models, responses.
- Automating API client generation 

**Describe the solution you'd like to see**
The [openapi v3](https://swagger.io/specification/) is the standard for defining API in structured and sharing it with the others. 
Users can explore REST API in web browser, e.g: https://petstore.swagger.io
There are many tools that supports client generation from the openapi spec, e.g.: https://github.com/OpenAPITools/openapi-generator.

**Describe alternatives you've considered**
n/a

P.S.
If this feature is welcome, then I am eager to help you with this.

**Comment by pbalogh-sa** [comment]
Sounds good. Thanks!
