### ISSUE TITLE
Leveraging SA token to access EKS cluster

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#47]
**Is your feature request related to a problem? Please describe.**

Having just SA token is not sufficient to access EKS cluster.

**Describe the solution you'd like to see**
Since this solution aims to solve  managed oidc authentication issue for managed clusters, It would be great to show how to do it for the biggest cloud providers: AKS, EKS, GKS

**Describe alternatives you've considered**
n/a

**Additional context**
 For EKS clusters 

performing just:
```
k --token $token --certificate-authority ca.crt --server $APISERVER get po 
error: You must be logged in to the server (Unauthorized)
```

after annotating service account with AWS role:
```
k --token $token --certificate-authority ca.crt --server $APISERVER get po 
error: the server doesn't have a resource type "po"
```

**Comment by j-zimnowoda** [comment]
I am really curious if you have ever had this issue. If so, then how have you solved it.
Regards

**Comment by Morriz** [comment]
Maybe it is just what it says? That "po" does not exist? Did you try with "pod"?

**Comment by j-zimnowoda** [comment]
> Maybe it is just what it says? That "po" does not exist? Did you try with "pod"?

yes, I did. Same error.

**Comment by pbalogh-sa** [comment]
Hi @j-zimnowoda , I can authenticate with SA token to my EKS cluster.
``` 
kubectl --token $TOKEN --server  https://0A9D8FA06B1F6CEB05E4210D0A7A089F.gr7.us-west-2.eks.amazonaws.com get pod -n kube-system
NAME                       READY   STATUS    RESTARTS   AGE
aws-node-96g2r             1/1     Running   0          65m
aws-node-dv79l             1/1     Running   0          66m
aws-node-m7hv4             1/1     Running   0          66m
coredns-5946c5d67c-tjbwl   1/1     Running   0          71m
coredns-5946c5d67c-tkdnb   1/1     Running   0          71m
kube-proxy-46sxk           1/1     Running   0          65m
kube-proxy-h5ndg           1/1     Running   0          66m
kube-proxy-jjhht           1/1     Running   0          66m
```

**Comment by j-zimnowoda** [comment]
@pbalogh-sa thanks for your answer.
I did not decode the secret with `base64 --decode` and that was the issue.
The jet-to-rbac works out of the box - great! It's a very promising solution for having cloud native oidc login to the closter.

Btw, I am going to integrate `jwt-to-rbac` with the containers platform that I and other folks are working on.
Take a look, there is a lot of valuable and interesting stuff: https://github.com/redkubes/otomi-core

**Comment by pbalogh-sa** [comment]
I close the issue but feel free to reopen it if you have additional questions.
