### ISSUE TITLE
Do not allow clients to set TTL for SA token 

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/jwt-to-rbac#52]
**Is your feature request related to a problem? Please describe.**
The SA token TTL is a policy that cluster administrator should enforce, not a user that is requesting SA token.

**Describe the solution you'd like to see**
I propose to
- expose `rbachandler. tokenTTL` property in helm chart
- remove POST http://localhost:5555/tokens/<saname> endpoint from the app

**Describe alternatives you've considered**
n/a

**Comment by pbalogh-sa** [comment]
The original concept was that the TTL was could be set during every token generation. But currently, this approach isn't necessary anymore.  So we can change this behavior.

**Comment by pbalogh-sa** [comment]
@j-zimnowoda 
I created a flag for enabling the token creation via API but by default, this feature is turned off.
In this way, we can keep the backward compatibility for a while.
