### ISSUE TITLE
Create service account fails

### ISSUE THREAD

**Issue by danielwhatmuff** [banzaicloud/jwt-to-rbac#7]
I posted my valid JWT to the `jwt-to-rbac` service and got this error back:

`create serviceaccount failed: ServiceAccount "" is invalid: metadata.name: Required value: name or generateName is required`

Tracked down to here:
https://github.com/banzaicloud/jwt-to-rbac/blob/195607afef005972d3fc0a2c4d557f3d19006d6a/pkg/rbachandler/rbac_handler.go#L230

And relevant line here:
https://github.com/banzaicloud/jwt-to-rbac/blob/195607afef005972d3fc0a2c4d557f3d19006d6a/pkg/rbachandler/rbac_handler.go#L342

My JWT structure issued from dex using the github connector:

```
{
  "groups": [
    "org:group1",
    "org:group2"
  ],
  "sub": "sub",
  "iss": "https://dex.example.com",
  "email_verified": true,
  "name": "Daniel Whatmuff",
  "at_hash": "hash",
  "exp": 1550770904,
  "iat": 1550767304,
  "email": "myemail",
  "aud": "kubernetes"
}
```

If its trying to use `name` obviously the creation will fail with something like:

`The ServiceAccount "Daniel Whatmuff" is invalid: metadata.name: Invalid value: "Daniel Whatmuff": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

But looks like its trying to use `FederatedClaimas.UserID`...?

Also, I noticed a few FederatedClaim**a**s - are they typos of FederatedClaims?

**Comment by pbalogh-sa** [comment]
Hello @danielwhatmuff, currently jwt-to-rbac doesn't handle jwt-s issued with github connector. This is on our roadmap, the next week we'll release it.

**Comment by pbalogh-sa** [comment]
@danielwhatmuff thanks for your notice about typo, but it doesn't cause error due to defined struct use FederatedClaimas as well.
https://github.com/banzaicloud/jwt-to-rbac/blob/ba28d3116e34c6b7922356675a5bcccfe2184324/pkg/tokenhandler/token_handler.go#L33-L36

**Comment by pbalogh-sa** [comment]
@danielwhatmuff you have to add federated:id to oauth2config scope in your auth app as well.
The jwt structure has to be like this: 
```
{
  "iss": "http://dex/dex",
  "sub": "sub",
  "aud": "example-app",
  "exp": 1550864685,
  "iat": 1550778285,
  "at_hash": "hash",
  "email": "p.balogh.sa@gmail.com",
  "email_verified": true,
  "groups": [
    "pokeorg",
    "pokeorg:admin",
    "pokeorg:developer"
  ],
  "name": "Peter Balogh",
  "federated_claims": {
    "connector_id": "github",
    "user_id": "userid"
  }
}
```

**Comment by pbalogh-sa** [comment]
Hello @danielwhatmuff, could you be so kind to take a try now. Readme updated as well:
https://github.com/banzaicloud/jwt-to-rbac#define-github-custom-roles-in-config
